services:
  database:
    image: mysql:8.0.41
    container_name: hero_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hero_db
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-proot']
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: hero_api
    environment:
      DATABASE_URL: mysql://root:root@database:3306/hero_db
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    restart: always
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: hero_frontend
    environment:
      VITE_BASE_API: http://localhost:3000
    ports:
      - 80:80
    restart: always
    depends_on:
      - api
volumes:
  mysql_data: {}
